# general cfg
image_flip:             True
max_depth:              15
domain:                 rgb

# ros topics
vizTopic:               /viplanner/viz_path_rgb
imgTopic:               /wide_angle_camera_front/image_raw/compressed
infoTopic:              /wide_angle_camera_front/camera_info
goalTopic:              /mp_waypoint
pathTopic:              /viplanner/path

# frame ids
robot_frame:            base
odom_frame:             odom
