# planning
main_freq:              10
image_flip:             False
conv_dist:              0.5
max_depth:              15
overlap_ratio_thres:    0.80
depth_zero_ratio_thres: 0.6
# network model
model_save:             models/vip_models/plannernet_env2azQ1b91cZZ_cam_mount_ep100_inputDepSem_costSem_optimSGD_new_cam_mount_combi_lossWidthMod_wgoal4.0_warehouse
# mmdet
# m2f_model_path:         models/mask2former_r50_8xb2-lsj-50e_coco-panoptic_20230118_125535-54df384a.pth
m2f_model_path:         models/mask2former_r50_lsj_8x2_50e_coco-panoptic_20220326_224516-11a44721.pth
# m2f_cfg_file:           ${HOME}/.local/lib/python3.8/site-packages/mmdet/.mim/configs/mask2former/mask2former_r50_8xb2-lsj-50e_coco-panoptic.py
m2f_cfg_file:           /home/${USER}/.local/lib/python3.8/site-packages/mmdet/.mim/configs/mask2former/mask2former_r50_8xb2-lsj-50e_coco-panoptic.py

# ros topics
depth_topic:            /depth_camera_front/depth/image_rect_raw
depth_info_topic:       /depth_camera_front/depth/camera_info
rgb_topic:              /depth_camera_front/color/image_raw/compressed
rgb_info_topic:         /depth_camera_front/color/camera_info
goal_topic:             /mp_waypoint
path_topic:             /viplanner/path
m2f_timer_topic:        /viplanner/m2f_timer
depth_uint_type:        True
compressed:             True
# frame ids
robot_id:               base  # also adjust in path_follower.launch
world_id:               odom
# fear reaction
is_fear_act:            False
buffer_size:            3
angular_thread:         0.3
track_dist:             0.5
# smart joystick
joyGoal_scale:          2.5
